version: "0.1.0.{build}"
install:
  - cmd: choco install mingw
  - ps: Invoke-WebRequest http://www.f2ko.de/downloads/cmdtools/sendkey.exe
build_script:
  - cmd: build.cmd /batch /buildonly
test_script:
  - cmd: build.cmd /test
artifacts:
  - path: "*.exe"
